### PR TITLE
New workflow to build and package frontend.

### PR DESCRIPTION
**Pull request by muehlefeldt**
Based on Pull request #38: Current front-end code merge into main. Should provide are more practical method of working with the front-end. Tests seem OK but issues may remain.

### CODE REVIEW

**Comment by muehlefeldt** [comment]
Tests should pass given a completed pull request #38. But do not ask me.

**Review by Gnieselbert — COMMENTED** [review]
build-frontend.yml approved

**Comment by muehlefeldt** [comment]
Should be OK now.

**Review by notandreas — APPROVED** [review]
works fine

**Pull request merged**
